/* Palette generated by Material Palette - materialpalette.com/indigo/pink */

export const BackgroundColor = {
   DefaultPrimary: "#3F51B5",
   DarkPrimary: "#303F9F",
   LightPrimary: "#C5CAE9",
   Accent: "#FF4081",
} as const;

export const TextColor = {
   LightPrimary: "#FFFFFF",
   DarkPrimary: "#212121",
   Secondary: "#757575",
} as const;
export const BorderColor = "#BDBDBD";

export const ColorPalette = {
   ...BackgroundColor,
   ...TextColor,
   BorderColor,
} as const;
